module.exports.from = function(company,email){
  return `${company}<${email}>`;
};
module.exports.inviteURL= function(authCode){
    return process.env.SYSTEM_HOST_URL+'/users/authenticate?authCode='+authCode;
};
module.exports.resetPasswordUrl = function(authCode){
    return process.env.SYSTEM_HOST_URL+'/users/recovery/'+authCode;
};
module.exports.inviteSubject = function(company){
    return `${company} Account Creation`;
};

module.exports.inviteBody = function(user,company,inviteUrl){
    return`<p>Dear ${user.firstname},</p>
    <p><b>Please Follow The Link Below To Create Your ${company} Account:</b></p>
    <p>Account Creation Link: <a href='${inviteUrl}'>Create Account</a></p>
    <p>Thanks, </p>
    <p>${company} Team</p>
    <br>
    <p>** This E-mail was Automatically Generated by the ${company} System **</p>
    <p>** An Administrator requested ${user.email} to create an account with ${company}**</p>
    <p>** If you believe this E-mail is a mistake please ignore it **</p>`;
};

module.exports.authUrl = function(){
  return process.env.SYSTEM_HOST_URL;
};

module.exports.authSubject = function(company){

    return `${company} Account Verified`;

};

module.exports.authBody = function(user,company,url){

    return `<p>${user.firstname},</p>
    <p><b>Account Successfully Verified and Created</b></p>
    <p>Your ${company} account associated with this email was successfully created!</p>
    <p><a href=${url}>Click Here</a> to go to the Login Screen:</p>
    <p>Thanks, </p>
    <p>${company} Team</p>
    <br>
    <p>** This E-mail was Automatically Generated by the ${company} System **</p>
    <p>** An Administrator requested ${user.email} to create an account with ${company}**</p>
    <p>** If you believe this E-mail is a mistake please ignore it **</p>`;

};

module.exports.projectAddSubject = function(project){
    return `You've been added to Project ${project.projectName}`;
};

module.exports.projectAddBody = function(user,project,company) {
    let template = `<p>${user.firstname},</p>
    <p><b>An Administrator has added you to view or work on: </b></p>
    <p>Project ${project.projectName}</p>
    <br>
    <p><b>The Folders You Were Invited to work on are:</b></p>`;
    project.folderPermissions.forEach(perm=>{
        template+=`<p>${perm.folderName}</p>`;
    });
    template += `<br><p>Thanks, </p>
    <p>${company} Team</p>
    <br>
    <p>** This E-mail was Automatically Generated by the ${company} System **</p>
    <p>** If you believe this E-mail is a mistake please ignore it **</p>`;
    return template;
};

module.exports.folderAddBody = function(user,project,folder,company) {
    return `<p>${user.firstname},</p>
    <p><b>You Have Been Added to Folder ${folder}:</b></p>
    <p>An Administrator has added you to view or work on Folder ${folder}.</p>
    <pre><p>${folder} is located within Project ${project}</p></pre>
    <p>${company} Team</p>
    <br>
    <p>** This E-mail was Automatically Generated by the ${company} System **</p>
    <p>** If you believe this E-mail is a mistake please ignore it **</p>`
};

module.exports.accountRecoverySubject = function(){
    return `Account Recovery Instructions`;
};
module.exports.accountRecoveryBody = function(user,resetUrl,company){
    return `<p>${user.firstname},</p>
    <p>A request was submitted to reset your account password.</p>
    <p><b>Please click the link below to reset your password:</b></p>
    <p>Account Creation Link: <a href='${resetUrl}'>Reset Password</a></p>
    <p>${company} Team</p>
    <br>
    <p>** This E-mail was Automatically Generated by the ${company} System **</p>
    <p>** If you believe this E-mail is a mistake please ensure your account security with the system administrator **</p>`
};
