const mailer = require('nodemailer');

class System_Mailer{

    constructor(service,email,pass){

        this.service = service;
        this.email = email;
        this.pass = pass;
        this.from = '"Novitious" <'+this.email+'>';

        this.transporter = mailer.createTransport({
            service: this.service,
            auth: {
                user: this.email,
                pass: this.pass
            }
        });
    }

    addUserEmail(firstname,email,authcode){
        console.log('mail: ' + authcode);
        const mailOptions = {
            from: this.from,
            to: email,
            subject: 'Novitious Account Creation',
            text: 'That was easy!',
            html: `<p>Dear ${firstname},</p>
                   <p><b>Please Follow The Link Below To Create Your Novitious Account:</b></p>
                   <p>Account Creation Link: <a href='http://localhost:3000/newuser?authcode=${authcode}'>http://localhost:3000/newuser?authcode=${authcode}</a></p>
                   <p>Thanks, </p>
                   <p>Novitious Team</p>
                   <br>
                   <p>** This E-mail was Automatically Generated by the Novitious System **</p>
                   <p>** An Administrator requested ${email} to create an account with Novitious**</p>
                   <p>** If you believe this E-mail is a mistake please ignore it **</p>`

        };
        return this.transporter.sendMail(mailOptions).
        then((info)=>{
            return info;
        }).catch((err)=>{
            console.log(err);
            return err;
        });

}



}
module.exports = {System_Mailer:System_Mailer};