const mailer = require('nodemailer');

class System_Mailer{

    constructor(service,email,pass){

        this.service = service;
        this.email = email;
        this.pass = pass;
        this.from = '"Novitious" <'+this.email+'>';

        this.transporter = mailer.createTransport({
            service: this.service,
            auth: {
                user: this.email,
                pass: this.pass
            }
        });
    }

    invite(firstname,email,authcode){

        let success = true;

        const mailOptions = {
            from: this.from,
            to: email,
            subject: 'Novitious Account Creation',
            text: 'Novitious Account Creation',
            html: `<p>Dear ${firstname},</p>
                   <p><b>Please Follow The Link Below To Create Your Novitious Account:</b></p>
                   <p><pre>Account Creation Link: <a href='http://74.70.197.249/users/authenticate?authcode=${authcode}'>Create Account</a></pre></p>
                   <p>Thanks, </p>
                   <p>Novitious Team</p>
                   <br>
                   <p>** This E-mail was Automatically Generated by the Novitious System **</p>
                   <p>** An Administrator requested ${email} to create an account with Novitious**</p>
                   <p>** If you believe this E-mail is a mistake please ignore it **</p>`

        };

        this.transporter.sendMail(mailOptions,(info,err)=>{
            if(err){success = false}
            success = true;
        });
        return success;


    }
    projectAdd(firstname,email,project){

        let success = true;

        const mailOptions = {
            from: this.from,
            to: email,
            subject: 'Novitious Project Permission',
            text: 'Novitious Project Permission',
            html: `<p>${firstname},</p>
                   <p><b>You Have Been Added to Project ${project}:</b></p>
                   <pre><p>An Administrator has added you to view or work on Project ${project}</p></pre>
                   <p>Novitious Team</p>
                   <br>
                   <p>** This E-mail was Automatically Generated by the Novitious System **</p>
                   <p>** If you believe this E-mail is a mistake please ignore it **</p>`

        };

        this.transporter.sendMail(mailOptions,(info,err)=>{
            if(err){success = false}
            success = true;
        });
        return success;


    }
    folderAdd(firstname,email,folder,project){

        let success = true;

        const mailOptions = {
            from: this.from,
            to: email,
            subject: 'Novitious Folder Permission',
            text: 'Novitious Folder Permission',
            html: `<p>${firstname},</p>
                   <p><b>You Have Been Added to Folder ${folder}:</b></p>
                   <p><pre>An Administrator has added you to view or work on Folder ${folder}.</pre></p>
                   <pre><p>${folder} is located within Project ${project}</p></pre>
                   <p>Novitious Team</p>
                   <br>
                   <p>** This E-mail was Automatically Generated by the Novitious System **</p>
                   <p>** If you believe this E-mail is a mistake please ignore it **</p>`

        };

        this.transporter.sendMail(mailOptions,(info,err)=>{
            if(err){success = false}
            success = true;
        });
        return success;


    }
    fileAdd(firstname,email,file,project){

        let success = true;

        const mailOptions = {
            from: this.from,
            to: email,
            subject: 'Novitious File Permission',
            text: 'Novitious File Permission',
            html: `<p>${firstname},</p>
                   <p><b>You Have Been Given Access to ${file}:</b></p>
                   <p><pre>An Administrator has added you to view or download ${file}.</pre></p>
                   <pre><p>${file} is located within Project ${project}</p></pre>
                   <p>Novitious Team</p>
                   <br>
                   <p>** This E-mail was Automatically Generated by the Novitious System **</p>
                   <p>** If you believe this E-mail is a mistake please ignore it **</p>`

        };

        this.transporter.sendMail(mailOptions,(info,err)=>{
            if(err){success = false}
            success = true;
        });
        return success;


    }
    folderFileAdd(firstname,email,file,project,folder){

        let success = true;

        const mailOptions = {
            from: this.from,
            to: email,
            subject: 'Novitious File Permission',
            text: 'Novitious File Permission',
            html: `<p>${firstname},</p>
                   <p><b>You Have Been Given Access to ${file}:</b></p>
                   <p><pre>An Administrator has added you to view or download ${file}.</pre></p>
                   <pre><p>${file} is located within Project ${project} inside the ${folder} folder</p></pre>
                   <p>Novitious Team</p>
                   <br>
                   <p>** This E-mail was Automatically Generated by the Novitious System **</p>
                   <p>** If you believe this E-mail is a mistake please ignore it **</p>`

        };

        this.transporter.sendMail(mailOptions,(info,err)=>{
            if(err){success = false}
            success = true;
        });
        return success;


    }
    notify(action,values){

        if(action === 'USER INVITED'){

            this.invite(values.firstname,values.email,values.authCode);

        }else if(action === 'PROJECT ADD'){
            this.projectAdd(values.user.firstname,values.user.email,values.project);
        }else if( action === 'FOLDER ADD'){
            this.folderAdd(values.user.firstname,values.user.email,values.folder,values.project);
        }else if('FILE ADD'){
            this.fileAdd(values.user.firstname,values.user.email,values.file,values.project);
        }else if('FOLDER FILE ADD'){
            this.folderFileAdd(values.user.firstname,values.user.email,values.file,values.project,values.folder);
        }

    }



}
module.exports = {System_Mailer:System_Mailer};
